name: issue1207

on: 
  workflow_dispatch:

jobs:
  setup-node:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Node.js with check-latest
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        check-latest: true

    - name: Verify Latest Node.js Version
      run: node -v
