name: PR1240

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13, ubuntu-24.04-arm]
        node-versions: [18, 21]
     
    steps:
      - uses: actions/checkout@v4
      - uses: marco-ippolito/setup-node@mirror
        with:
          node-version: ${{ matrix.node-versions }}
          mirror: 'https://nodejs.org/'
          mirror-token: ${{secrets.GITHUB_TOKEN}}
      - name: Verify Node.js installation
        run: node -v    
      

  test-non-lts:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-13, ubuntu-24.04-arm]
     
    steps:
      - uses: actions/checkout@v4
      - uses: marco-ippolito/setup-node@mirror
        with:
          node-version: '23'
          mirror: 'https://nodejs.org/'
          mirror-token: ${{secrets.GITHUB_TOKEN}}
      - name: Verify Node.js installation
        run: node -v    
     
